project:
  type: website

website:
  title: "Simon Steinlin"
  site-url: "https://zetsy0.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: projects.qmd
        text: Personal Projects
    background: light
    foreground: dark
  page-footer:
    center: "© 2026 Simon"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true